import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "My Booking": "My Booking",
          "Payments": "Payments",
          "Rate us": "Rate us",
          "rafer": "Refer & Earn",
        },
        'hi_US': {
          "My Booking": "मेरी बुकिंग",
          "Wallet": "बटुआ",
          "Profile": "प्रोफ़ाइल",
          "Notification": "अधिसूचना",
          "Country": "देश",
          "Language": "भाषा",
          "English(US)": "अंग्रेजी",
          "Help Center": "सहायता केंद्र",
          "Invite Friends": "मित्रों को आमंत्रित करें",
          "Logout": "लॉग आउट",
          "Dark Mode": "डार्क मोड",
          "Are you sure you want to log out?":
              "क्या आप लॉग आउट करना चाहते हैं?",
          "Cancle": "कैंकल",
          "Yes, Remove": "हाँ, हटाओ",
          "Coupons": "कूपन",
          "Property Title": "संपत्ति का शीर्षक",
          "Full Name": "पूरा नाम",
          "Please enter your name": "कृपया अपना नाम दर्ज करें",
          "Book For Someone": "किसी के लिए बुक करें",
          "Your Information Details": "आपकी जानकारी का विवरण",
          "First Name": "पहला नाम",
          "Please enter your first name": "कृपया अपना पहला नाम दें",
          "Last Name": "उपनाम",
          "Please enter your last name": "कृपया अपना अंतिम नाम दर्ज करें",
          "Email": "ईमेल",
          "Please enter your email": "अपना ईमेल दर्ज करें",
          "Mobile Number": "मोबाइल नंबर",
          "Please enter your number": "कृपया अपना नंबर दर्ज करें",
          "Continue": "जारी रखना",
          "Please fill all required fields": "कृपया सभी आवश्यक फ़ील्ड भरें",
          "Book Real Estate": "बुक रियल एस्टेट",
          "Select Date": "तारीख़ चुनें",
          "Check in": "चेक इन",
          "Check out": "चेक आउट",
          "Number of Guest": "अतिथि की संख्या",
          "Note to Owner (optional)": "स्वामी के लिए नोट (वैकल्पिक)",
          "Notes": "टिप्पणियाँ",
          "Booking for someone": "किसी के लिए बुकिंग",
          "Home": "घर",
          "Search": "खोज",
          "Favorite": "पसंदीदा",
          "Account": "खाता",
          "BUY": "खरीदना",
          "Sorry, Search Data Not Found": "क्षमा करें, खोज डेटा नहीं मिला",
          "Sorry, there is no any nearby \n category or data not found":
              "क्षमा करें, आस-पास कोई \n श्रेणी नहीं है या डेटा नहीं मिला है",
          "Apply": "आवेदन करना",
          "Available coupons": "उपलब्ध कूपन",
          "Use": "उपयोग",
          "E-Receipt": "ई-रसीद",
          "Date": "तारीख",
          "Tax": "कर",
          "Coupon": "कूपन",
          "Total": "कुल",
          "Name": "नाम",
          "Phone Number": "फ़ोन नंबर",
          "Payment Title": "भुगतान शीर्षक",
          "Transaction ID": "लेन-देन आईडी",
          "Copy": "कॉपी",
          "Status": "दर्जा",
          "Paid": "चुकाया गया",
          "Review": "समीक्षा",
          "Leave a Review": "समीक्षा लिखें",
          "How was your experience": "आपका अनुभव कैसा रहा",
          "Write Your Review": "अपना आलेख लिखो",
          "Your review here...": "यहां आपकी समीक्षा...",
          "Maybe Later": "शायद बाद में",
          "Submit": "जमा करना",
          "Helps & FAQs": "सहायता और अक्सर पूछे जाने वाले प्रश्न",
          "Favorites": "पसंदीदा",
          "Sorry, Favorite List Empty": "क्षमा करें, पसंदीदा सूची खाली है",
          "Remove from Favorites?": "पसंदीदा से निकालें?",
          "Featured": "प्रदर्शित",
          "Gallary": "गैलरी",
          "Hello Welcome 👋": "नमस्कार स्वागत है 👋",
          "User": "उपयोगकर्ता",
          "See All": "सभी देखें",
          "Our Recommendation": "हमारी सिफारिश",
          "Search...": "खोज...",
          "Suggested": "सुझाव दिया",
          "Let's sign you in.": "आइए आपको साइन इन करते हैं",
          "Welcome back. You've been missed!":
              "वापसी पर स्वागत है। आपको याद किया गया है!",
          "Please enter your mobile number": "अपना मोबाइल नंबर दर्ज करें",
          "Please enter your password": "अपना पासवर्ड दर्ज करें",
          "Password": "पासवर्ड",
          "Remember me": "पहचाना की नहीं",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Login": "लॉग इन करें",
          "OR": "या",
          "Continue as a Guest": "अतिथि के रूप में जारी रखें",
          "Don't have an account?": "खाता नहीं है?",
          "Sign Up": "साइन अप करें",
          "Massage": "मालिश",
          "Active": "सक्रिय",
          "Completed": "पुरा होना।",
          "Go & Book your favorite service": "जाओ और अपनी पसंदीदा सेवा बुक करो",
          "New": "नया",
          "We'll let you know when we\nget news for you":
              "हम आपको बताएंगे कि जब हम आपके लिए समाचार प्राप्त करेंगे",
          "The Perfect choice for": "के लिए बिल्कुल सही विकल्प",
          "your future": "आपका भविष्य",
          "Login With Phone Number": "फोन नंबर से लॉगिन करें",
          "Verification Code": "सत्यापन कोड",
          "We have sent the code verification to":
              "हमने कोड सत्यापन को भेज दिया है",
          "Didn't receive code?": "कोड नहीं मिला?",
          "Resend New Code": "नया कोड पुनः भेजें",
          "Verify": "सत्यापित करना",
          "Please enter your valid OTP": "कृपया अपना वैध ओटीपी दर्ज करें",
          "Create Your New Password": "अपना नया पासवर्ड बनाएं",
          "Conform Password": "पासवर्ड अनुरूप करें",
          "Reset Password": "Reset Password",
          "Please enter your phone number to request a\npassword reset":
              "पासवर्ड रीसेट करने का\nअनुरोध करने के लिए कृपया अपना फोन नंबर दर्ज करें",
          "Request OTP": "ओटीपी का अनुरोध करें",
          "You remember your password?": "आपको अपना पासवर्ड याद है?",
          "Review Summary": "समीक्षा सारांश",
          "Remove": "निकालना",
          "Add": "जोड़ना",
          "Pay from Wallet": "वॉलेट से भुगतान करें",
          "Wallet Balance": "वॉलेट बैलेंस",
          "Available for Payment ": "भुगतान हेतु उपलब्ध है",
          "Congratulations!": "बधाई हो!",
          " v successfully\n booked. You can chack your booking\n on the menu Profile":
              "आधुनिक अपार्टमेंट सफलतापूर्वक\n बुक किया गया। आप मेन्यू प्रोफ़ाइल पर अपनी बुकिंग\n देख सकते हैं",
          "View E-Receipt": "ई-रसीद देखें",
          "Select Payment Method": "भुगतान का तरीका चुनें",
          "Add Your payment information": "अपनी भुगतान जानकारी जोड़ें",
          "What number is written on card?": "कार्ड पर कौन सा नंबर लिखा है?",
          "Number behind the card": "कार्ड के पीछे नंबर",
          "CVV": "सीवीवी",
          "MM/YY": "महीना साल",
          "Expiry Date": "समाप्ति तिथि",
          "Payment card is valid": "भुगतान कार्ड मान्य है",
          "Select Country": "बटुआ",
          "Get Started!": "शुरू हो जाओ!",
          "Create an account to continue.": "जारी रखने के लिए एक खाता बनाएँ।",
          "Email Address": "मेल पता",
          "Referral code (optional)": "रेफ़रल कोड (वैकल्पिक)",
          "By creating an account,you agree to our":
              "एक खाता बनाकर, आप हमारी सहमति देते हैं",
          "Terms and Condition": "नियम व शर्तें",
          "Please select Terms and Condition": "कृपया नियम और शर्त चुनें",
          "Already have an account?": "क्या आपके पास पहले से एक खाता मौजूद है?",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "अपनी संपत्तियों को आसानी से प्रबंधित करें और \nप्रतिक्रियाओं के बारे में तत्काल अलर्ट प्राप्त करें",
          "Listing Agent": "लिस्टिंग एजेंट",
          "Partner": "साझेदार",
          "Overview": "अवलोकन",
          "Read more": "और पढ़ें",
          "Show less": "कम दिखाएं",
          "Facillities": "सुविधाएँ",
          "Location": "जगह",
          "Price": "कीमत",
          "Book": "किताब",
          "Contacted": "व्यक्ति से संपर्क किया",
          "Enquiry Already Send!!": "जांच पहले से ही भेजें!!",
          "Inquiry": "जाँच करना",
          "Please login and send enquery": "कृपया लॉगिन करें और पूछताछ भेजें",
          "Update": "अद्यतन",
          "Add Wallet": "बटुआ जोड़ें",
          "Your current Balance": "आपका वर्तमान शेष",
          "Add Amount": "राशि जोड़ें",
          "Refer a Friend": "एक मित्र को सूचित करें",
          "Share the referral link with your friends":
              "अपने दोस्तों के साथ रेफ़रल लिंक साझा करें",
          "History": "इतिहास",
          "ADD AMOUNT": "राशि जोड़ें",
          "Please don`t press back until the transaction is complete":
              "लेन-देन पूरा होने तक कृपया वापस न दबाएं",

          "Amount": "मात्रा",
          "days": "दिन",
          "Booking Date": "बुक करने की तिथि",
          "/night": "/रात",
          "Beds": "बेड",
          "Bath": "नहाना",
          "sqft": "वर्गफुट",
          "About this space": "इस स्पेस के बारे में",
          "What this place offers": "यह स्थान क्या प्रदान करता है",
          "Allowed Max": "अनुमत मैक्स",
          "Guest": "अतिथि",
          "Not Paid": "भुगतान नहीं",
          "Friend get": "मित्र प्राप्त करें",
          "on their first complete\ntransaction": "उनके पहले पूर्ण\nलेन-देन पर",
          "You get": "आपको मिला",
          "on your wallet": "आपके बटुए पर",
          "for Each\n Friend you refer":
              "प्रत्येक\n मित्र के लिए जिसे आप संदर्भित करते हैं",
          "Earn": "कमाना",
          "Are you sure you want to delete account?":
              "क्या आप वाकई खाता हटाना चाहते हैं?",
          "Delete Account": "खाता हटा दो",
          "founds": "पाया",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
        },
        'ar_US': {
          "My Booking": "الحجز",
          "Wallet": "محفظة",
          "Profile": "حساب تعريفي",
          "Notification": "إشعار",
          "Country": "دولة",
          "Language": "لغة",
          "English(US)": "الإنجليزية (الولايات المتحدة)",
          "Help Center": "مركز المساعدة",
          "Invite Friends": "ادعو أصدقاء",
          "Logout": "تسجيل خروج",
          "Dark Mode": "الوضع الداكن",
          "Are you sure you want to log out?":
              "هل أنت متأكد أنك تريد تسجيل الخروج؟, ",
          "Cancle": "إلغاء",
          "Yes, Remove": "نعم ، قم بإزالة",
          "Coupons": "كوبونات",
          "Property Title": "عنوان الملكية",
          "Full Name": "الاسم الكامل",
          "Please enter your name": "من فضلك أدخل إسمك",
          "Book For Someone": "كتاب لشخص ما",
          "Your Information Details": "تفاصيل المعلومات الخاصة بك",
          "First Name": "الاسم الأول",
          "Please enter your first name": "يرجى ادخال الاسم الاول",
          "Last Name": "اسم العائلة",
          "Please enter your last name": "الرجاء إدخال اسمك الأخير",
          "Email": "بريد إلكتروني",
          "Please enter your email": "رجاءا أدخل بريدك الإلكتروني",
          "Mobile Number": "رقم الهاتف المحمول",
          "Please enter your number": "الرجاء إدخال رقمك",
          "Continue": "يكمل",
          "Please fill all required fields": "يرجى تعبئة جميع الحقول المطلوبة",
          "Book Real Estate": "كتاب العقارات",
          "Select Date": "حدد تاريخ",
          "Check in": "تحقق في",
          "Check out": "الدفع",
          "Number of Guest": "عدد الحضور",
          "Note to Owner (optional)": "ملاحظة للمالك (اختياري)",
          "Notes": "ملحوظات",
          "Booking for someone": "الحجز لشخص ما",
          "Home": "بيت",
          "Search": "يبحث",
          "Favorite": "مفضل",
          "Account": "حساب",
          "BUY": "يشتري",
          "Sorry, Search Data Not Found":
              "عذرا ، لم يتم العثور على بيانات البحث",
          "Sorry, there is no any nearby \n category or data not found":
              "معذرةً ، لا توجد أية فئة قريبة \n أو بيانات غير موجودة",
          "Apply": "يتقدم",
          "Available coupons": "القسائم المتاحة",
          "Use": "يستخدم",
          "E-Receipt": "إيصال إلكتروني",
          "Date": "تاريخ",
          "Tax": "ضريبة",
          "Coupon": "قسيمة",
          "Total": "المجموع",
          "Name": "اسم",
          "Phone Number": "رقم التليفون",
          "Payment Title": "عنوان الدفع",
          "Transaction ID": "رقم المعاملة",
          "Copy": "ينسخ",
          "Status": "حالة",
          "Paid": "مدفوع",
          "Review": "مراجعة",
          "Leave a Review": "ترك التعليق",
          "How was your experience": "كيف كانت تجربتك",
          "Write Your Review": "اكتب مراجعتك",
          "Your review here...": "رأيك هنا ...",
          "Maybe Later": "ربما في وقت لاحق",
          "Submit": "يُقدِّم",
          "Helps & FAQs": "يساعد والأسئلة الشائعة",
          "Favorites": "المفضلة",
          "Sorry, Favorite List Empty": "عذرا ، قائمة المفضلة فارغة",
          "Remove from Favorites?": "إزالة من المفضلة؟",
          "Featured": "متميز",
          "Gallary": "معرض",
          "Hello Welcome 👋": "مرحبا مرحبا 👋",
          "User": "مستخدم",
          "See All": "اظهار الكل",
          "Our Recommendation": "توصياتنا",
          "Search...": "يبحث...",
          "Suggested": "مقترح",
          "Let's sign you in.": "دعنا نسجل دخولك.",
          "Welcome back. You've been missed!": "مرحبًا بعودتك. لقد فاتك!",
          "Please enter your mobile number": "الرجاء إدخال رقم هاتفك المحمول",
          "Please enter your password": "من فضلك أدخل رقمك السري",
          "Password": "كلمة المرور",
          "Remember me": "تذكرنى",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Login": "تسجيل الدخول",
          "OR": "أو",
          "Continue as a Guest": "تواصل كضيف",
          "Don't have an account?": "ليس لديك حساب؟",
          "Sign Up": "اشتراك",
          "Massage": "تدليك",
          "Active": "نشيط",
          "Completed": "مكتمل",
          "Go & Book your favorite service": "اذهب وحجز الخدمة المفضلة لديك",
          "New": "جديد",
          "We'll let you know when we\nget news for you":
              "سنخبرك عندما \n نحصل على أخبار لك",
          "The Perfect choice for": "الخيار الأمثل لـ",
          "your future": "مستقبلك",
          "Login With Phone Number": "تسجيل الدخول برقم الهاتف",
          "Verification Code": "رمز التحقق",
          "We have sent the code verification to": "لقد أرسلنا رمز التحقق إلى",
          "Didn't receive code?": "لم تتلق رمز؟",
          "Resend New Code": "إعادة إرسال رمز جديد",
          "Verify": "يؤكد",
          "Please enter your valid OTP": "الرجاء إدخال OTP الخاص بك صالح",
          "Create Your New Password": "أنشئ كلمة مرورك الجديدة",
          "Conform Password": "تطابق كلمة المرور",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Please enter your phone number to request a\npassword reset":
              "الرجاء إدخال رقم هاتفك لطلب \n إعادة تعيين كلمة المرور",
          "Request OTP": "طلب OTP",
          "You remember your password?": "هل تتذكر كلمة المرور الخاصة بك؟",
          "Review Summary": "مراجعة الملخص",
          "Remove": "يزيل",
          "Add": "يضيف",
          "Pay from Wallet": "ادفع من Wallet",
          "Wallet Balance": "رصيد المحفظة",
          "Available for Payment ": "متاح للدفع",
          "Congratulations!": "تهانينا!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "تم حجز الشقة الحديثة بنجاح \n. يمكنك متابعة الحجز الخاص بك \n في ملف تعريف القائمة",
          "View E-Receipt": "عرض الإيصال الإلكتروني",
          "Select Payment Method": "اختار طريقة الدفع",
          "Add Your payment information": "أضف معلومات الدفع الخاصة بك",
          "What number is written on card?": "ما هو الرقم المكتوب على البطاقة؟",
          "Number behind the card": "الرقم خلف البطاقة",
          "CVV": "CVV",
          "MM/YY": "شهر / سنة",
          "Expiry Date": "تاريخ الانتهاء",
          "Payment card is valid": "بطاقة الدفع صالحة",
          "Select Country": "حدد الدولة",
          "Get Started!": "البدء!",
          "Create an account to continue.": "إنشاء حساب للمتابعة.",
          "Email Address": "عنوان البريد الإلكتروني",
          "Referral code (optional)": "إحالة قانون (اختياري)",
          "By creating an account,you agree to our":
              "من خلال إنشاء حساب ، فإنك توافق على",
          "Terms and Condition": "أحكام وشروط",
          "Please select Terms and Condition": "الرجاء تحديد الشروط والاحكام",
          "Already have an account?": "هل لديك حساب؟",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "قم بإدارة ممتلكاتك بسهولة \n واحصل على تنبيه فوري حول الردود",
          "Listing Agent": "وكيل القيد",
          "Partner": "شريك",
          "Overview": "ملخص",
          "Read more": "اقرأ أكثر",
          "Show less": "عرض أقل",
          "Facillities": "المرافق",
          "Location": "موقع",
          "Price": "سعر",
          "Book": "كتاب",
          "Contacted": "تم الاتصال",
          "Enquiry Already Send!!": "استفسار أرسل بالفعل !!",
          "Inquiry": "سؤال",
          "Please login and send enquery":
              "الرجاء تسجيل الدخول وإرسال الاستفسار",
          "Update": "تحديث",
          "Add Wallet": "أضف المحفظة",
          "Your current Balance": "رصيدك الحالي",
          "Add Amount": "أضف المبلغ",
          "Refer a Friend": "أوص أحد الأصدقاء",
          "Share the referral link with your friends":
              "شارك رابط الإحالة مع أصدقائك",
          "History": "تاريخ",
          "ADD AMOUNT": "أضف المبلغ",
          "Please don`t press back until the transaction is complete":
              "من فضلك لا تضغط مرة أخرى حتى تكتمل المعاملة",
          "Amount": "كمية",
          "days": "أيام",
          "Booking Date": "تاريخ الحجز",
          "/night": "/ليلة",
          "Beds": "سرير",
          "Bath": "حمام",
          "sqft": "قدم مربع",
          "About this space": "حول هذا الفضاء",
          "What this place offers": "ما يقدمه هذا المكان",
          "Allowed Max": "يسمح ماكس",
          "Guest": "ضيف",
          "Not Paid": "غير مدفوع",
          "Friend get": "الحصول على صديق",
          "on their first complete\ntransaction": "في أول معاملة \n مكتملة لهم",
          "You get": "لقد حصلت",
          "on your wallet": "على محفظتك",
          "for Each\n Friend you refer": "لكل \n صديق تشير إليه",
          "Earn": "يكسب",
          "Are you sure you want to delete account?":
              "هل أنت متأكد أنك تريد حذف الحساب؟",
          "Delete Account": "حذف الحساب",
          "founds": "يؤسس",
        },
        'fr_US': {
          "My Booking": "Ma réservation",
          "Wallet": "Portefeuille",
          "Profile": "Profil",
          "Notification": "Notification",
          "Country": "Pays",
          "Language": "Langue",
          "English(US)": "Anglais (États-Unis)",
          "Help Center": "Centre d'aide",
          "Invite Friends": "Inviter des amis",
          "Logout": "Se déconnecter",
          "Dark Mode": "Mode sombre",
          "Are you sure you want to log out?":
              "Êtes-vous sûr de vouloir vous déconnecter?,",
          "Cancle": "Annuler",
          "Yes, Remove": "Oui, supprimer",
          "Coupons": "Coupons",
          "Property Title": "Titre de propriété",
          "Full Name": "Nom et prénom",
          "Please enter your name": "S'il vous plaît entrez votre nom",
          "Book For Someone": "Réserver pour quelqu'un",
          "Your Information Details": "Vos informations détaillées",
          "First Name": "Prénom",
          "Please enter your first name": "Entrez votre prénom s'il vous plait",
          "Last Name": "Nom de famille",
          "Please enter your last name": "Veuillez entrer votre nom de famille",
          "Email": "E-mail",
          "Please enter your email": "Veuillez saisir votre e-mail",
          "Mobile Number": "Numéro de portable",
          "Please enter your number": "Veuillez entrer votre numéro",
          "Continue": "Continuer",
          "Please fill all required fields":
              "Veuillez remplir tous les champs obligatoires",
          "Book Real Estate": "Réserver un bien immobilier",
          "Select Date": "Sélectionner une date",
          "Check in": "Enregistrement",
          "Check out": "Vérifier",
          "Number of Guest": "Nombre d'invités",
          "Note to Owner (optional)": "Note au propriétaire (facultatif)",
          "Notes": "Remarques",
          "Booking for someone": "Réservation pour quelqu'un",
          "Home": "Maison",
          "Search": "Recherche",
          "Favorite": "Préféré",
          "Account": "Compte",
          "BUY": "ACHETER",
          "Sorry, Search Data Not Found":
              "Désolé, données de recherche introuvables",
          "Sorry, there is no any nearby \n category or data not found":
              "Désolé, il n'y a pas de catégorie \n à proximité ou de données introuvables",
          "Apply": "Appliquer",
          "Available coupons": "Coupons disponibles",
          "Use": "Utiliser",
          "E-Receipt": "Reçu électronique",
          "Date": "Date",
          "Tax": "Impôt",
          "Coupon": "Coupon",
          "Total": "Total",
          "Name": "Nom",
          "Phone Number": "Numéro de téléphone",
          "Payment Title": "Titre du paiement",
          "Transaction ID": "identifiant de transaction",
          "Copy": "Copie",
          "Status": "Statut",
          "Paid": "Payé",
          "Review": "Examen",
          "Leave a Review": "Laisser un commentaire",
          "How was your experience": "Comment était votre expérience",
          "Write Your Review": "Donnez votre avis",
          "Your review here...": "Votre avis ici...",
          "Maybe Later": "Peut-être plus tard",
          "Submit": "Soumettre",
          "Helps & FAQs": "Aides et FAQ",
          "Favorites": "Favoris",
          "Sorry, Favorite List Empty": "Désolé, la liste des favoris est vide",
          "Remove from Favorites?": "Retirer des favoris?",
          "Featured": "Mis en exergue",
          "Gallary": "Galerie",
          "Hello Welcome 👋": "Bonjour Bienvenue 👋",
          "User": "Utilisateur",
          "See All": "Voir tout",
          "Our Recommendation": "Notre recommandation",
          "Search...": "Recherche...",
          "Suggested": "Suggéré",
          "Let's sign you in.": "Nous allons vous connecter.",
          "Welcome back. You've been missed!":
              "Content de te revoir. Vous nous avez manqué !",
          "Please enter your mobile number":
              "Entrez s'il vous plaît votre numéro de téléphone",
          "Please enter your password":
              "s'il vous plait entrez votre mot de passe",
          "Password": "Mot de passe",
          "Remember me": "Souviens-toi de moi",
          "Forgot Password?": "Mot de passe oublié?",
          "Login": "Connexion",
          "OR": "OU",
          "Continue as a Guest": "Continuer en tant qu'invité",
          "Don't have an account?": "Vous n'avez pas de compte ?",
          "Sign Up": "S'inscrire",
          "Massage": "Massage",
          "Active": "Actif",
          "Completed": "Complété",
          "Go & Book your favorite service":
              "Go & Réservez votre service préféré",
          "New": "Nouveau",
          "We'll let you know when we\nget news for you":
              "Nous vous informerons lorsque nous aurons des nouvelles pour vous",
          "The Perfect choice for": "Le choix parfait pour",
          "your future": "ton futur",
          "Login With Phone Number": "Se connecter avec un numéro de téléphone",
          "Verification Code": "Le code de vérification",
          "We have sent the code verification to":
              "Nous avons envoyé la vérification du code à",
          "Didn't receive code?": "Vous n'avez pas reçu de code ?",
          "Resend New Code": "Renvoyer le nouveau code",
          "Verify": "Vérifier",
          "Please enter your valid OTP": "Veuillez entrer votre OTP valide",
          "Create Your New Password": "Créez votre nouveau mot de passe",
          "Conform Password": "Conformez le mot de passe",
          "Reset Password": "réinitialiser le mot de passe",
          "Please enter your phone number to request a\npassword reset":
              "Veuillez saisir votre numéro de téléphone pour demander une\nréinitialisation du mot de passe",
          "Request OTP": "Demander OTP",
          "You remember your password?":
              "Vous vous souvenez de votre mot de passe ?",
          "Review Summary": "Résumé des commentaires",
          "Remove": "Retirer",
          "Add": "Ajouter",
          "Pay from Wallet": "Payer depuis Wallet",
          "Wallet Balance": "Solde du portefeuille",
          "Available for Payment ": "Disponible pour paiement",
          "Congratulations!": "Toutes nos félicitations!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "Appartement moderne réservé avec succès. Vous pouvez vérifier votre réservation\n dans le menu Profil",
          "View E-Receipt": "Afficher le reçu électronique",
          "Select Payment Method": "Sélectionnez le mode de paiement",
          "Add Your payment information":
              "Ajoutez vos informations de paiement",
          "What number is written on card?":
              "Quel numéro est inscrit sur la carte ?",
          "Number behind the card": "Numéro derrière la carte",
          "CVV": "CVV",
          "MM/YY": "MM/AA",
          "Expiry Date": "Date expiration",
          "Payment card is valid": "La carte de paiement est valide",
          "Select Country": "Choisissez le pays",
          "Get Started!": "Commencer!",
          "Create an account to continue.": "Créez un compte pour continuer.",
          "Email Address": "Adresse e-mail",
          "Referral code (optional)": "Code de parrainage (facultatif)",
          "By creating an account,you agree to our":
              "En créant un compte, vous acceptez nos",
          "Terms and Condition": "Termes et conditions",
          "Please select Terms and Condition":
              "Veuillez sélectionner les termes et conditions",
          "Already have an account?": "Vous avez déjà un compte?",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "Gérez facilement vos propriétés et \nobtenez une alerte instantanée sur les réponses",
          "Listing Agent": "Agent inscripteur",
          "Partner": "Partenaire",
          "Overview": "Aperçu",
          "Read more": "En savoir plus",
          "Show less": "Montrer moins",
          "Facillities": "Installations",
          "Location": "Emplacement",
          "Price": "Prix",
          "Book": "Livre",
          "Contacted": "Contacté",
          "Enquiry Already Send!!": "Demande déjà envoyée !!",
          "Inquiry": "Demande",
          "Please login and send enquery":
              "Veuillez vous connecter et envoyer la demande",
          "Update": "Mise à jour",
          "Add Wallet": "Ajouter un portefeuille",
          "Your current Balance": "Votre solde actuel",
          "Add Amount": "Ajouter un montant",
          "Refer a Friend": "Référez un ami",
          "Share the referral link with your friends":
              "Partagez le lien de parrainage avec vos amis",
          "History": "Histoire",
          "ADD AMOUNT": "AJOUTER LE MONTANT",
          "Please don`t press back until the transaction is complete":
              "Veuillez ne pas appuyer sur retour jusqu'à ce que la transaction soit terminée",
          "Amount": "Montant",
          "days": "jours",
          "Booking Date": "Date de réservation",
          "/night": "/nuit",
          "Beds": "Des lits",
          "Bath": "Bain",
          "sqft": "pieds carrés",
          "About this space": "A propos de cet espace",
          "What this place offers": "Ce que cet endroit offre",
          "Allowed Max": "Max autorisé",
          "Guest": "Invité",
          "Not Paid": "Impayé",
          "Friend get": "Ami obtenir",
          "on their first complete\ntransaction":
              "lors de leur première\ntransaction complète",
          "You get": "Vous obtenez",
          "on your wallet": "sur votre portefeuille",
          "for Each\n Friend you refer": "pour chaque\n ami que vous parrainez",
          "Earn": "Gagner",
          "Are you sure you want to delete account?":
              "Voulez-vous vraiment supprimer le compte ?",
          "Delete Account": "Supprimer le compte",
          "founds": "fonde",
        },
        'de_US': {
          "My Booking": "Meine Buchung",
          "Wallet": "Geldbörse",
          "Profile": "Profil",
          "Notification": "Benachrichtigung",
          "Country": "Land",
          "Language": "Sprache",
          "English(US)": "Amerikanisches Englisch)",
          "Help Center": "Hilfezentrum",
          "Invite Friends": "Freunde einladen",
          "Logout": "Ausloggen",
          "Dark Mode": "Dunkler Modus",
          "Are you sure you want to log out?":
              "Möchten Sie sich wirklich abmelden?,",
          "Cancle": "Abbrechen",
          "Yes, Remove": "Ja, entfernen",
          "Coupons": "Gutscheine",
          "Property Title": "Eigentums Titel",
          "Full Name": "Vollständiger Name",
          "Please enter your name": "Bitte geben Sie Ihren Namen ein",
          "Book For Someone": "Buchen Sie für jemanden",
          "Your Information Details": "Ihre Informationsdetails",
          "First Name": "Vorname",
          "Please enter your first name": "Bitte geben Sie Ihren Vornamen ein",
          "Last Name": "Familienname, Nachname",
          "Please enter your last name": "Bitte geben Sie ihren Nachnamen ein",
          "Email": "Email",
          "Please enter your email": "Bitte geben Sie ihre E-Mail-Adresse ein",
          "Mobile Number": "Handy Nummer",
          "Please enter your number": "Bitte geben Sie Ihre Nummer ein",
          "Continue": "Weitermachen",
          "Please fill all required fields":
              "Bitte alle notwendigen Felder ausfüllen",
          "Book Real Estate": "Immobilien buchen",
          "Select Date": "Datum auswählen",
          "Check in": "Einchecken",
          "Check out": "Kasse",
          "Number of Guest": "Anzahl der Gäste",
          "Note to Owner (optional)": "Hinweis an Eigentümer (optional)",
          "Notes": "Anmerkungen",
          "Booking for someone": "Buchung für jemanden",
          "Home": "Heim",
          "Search": "Suchen",
          "Favorite": "Favorit",
          "Account": "Konto",
          "BUY": "BESORGEN",
          "Sorry, Search Data Not Found":
              "Entschuldigung, Suchdaten nicht gefunden",
          "Sorry, there is no any nearby \n category or data not found":
              "Entschuldigung, es gibt keine Kategorie in der Nähe \n oder es wurden keine Daten gefunden",
          "Apply": "Anwenden",
          "Available coupons": "Verfügbare Gutscheine",
          "Use": "Verwenden",
          "E-Receipt": "E-Beleg",
          "Date": "Datum",
          "Tax": "Steuer",
          "Coupon": "Coupon",
          "Total": "Gesamt",
          "Name": "Name",
          "Phone Number": "Telefonnummer",
          "Payment Title": "Zahlungstitel",
          "Transaction ID": "Transaktions-ID",
          "Copy": "Kopieren",
          "Status": "Status",
          "Paid": "Bezahlt",
          "Review": "Rezension",
          "Leave a Review": "Hinterlassen Sie eine Bewertung",
          "How was your experience": "Wie war Ihre Erfahrung",
          "Write Your Review": "Schreibe deine Rezension",
          "Your review here...": "Ihre Bewertung hier...",
          "Maybe Later": "Vielleicht später",
          "Submit": "Einreichen",
          "Helps & FAQs": "Hilfen und häufig gestellte Fragen",
          "Favorites": "Favoriten",
          "Sorry, Favorite List Empty": "Entschuldigung, Favoritenliste leer",
          "Remove from Favorites?": "Von Favoriten entfernen?",
          "Featured": "Hervorgehoben",
          "Gallary": "Galerie",
          "Hello Welcome 👋": "Hallo Willkommen 👋",
          "User": "Benutzer",
          "See All": "Alles sehen",
          "Our Recommendation": "Unsere Empfehlung",
          "Search...": "Suchen...",
          "Suggested": "Empfohlen",
          "Let's sign you in.": "Melden wir Sie an.",
          "Welcome back. You've been missed!":
              "Willkommen zurück. Du wurdest vermisst!",
          "Please enter your mobile number":
              "Bitte geben sie ihre Mobiltelefonnummer ein",
          "Please enter your password": "Bitte geben Sie Ihr Passwort ein",
          "Password": "Passwort",
          "Remember me": "Mich erinnern",
          "Forgot Password?": "Passwort vergessen?",
          "Login": "Anmeldung",
          "OR": "ODER",
          "Continue as a Guest": "Fahren Sie als Gast fort",
          "Don't have an account?": "Sie haben kein Konto?",
          "Sign Up": "Anmeldung",
          "Massage": "Massage",
          "Active": "Aktiv",
          "Completed": "Vollendet",
          "Go & Book your favorite service": "Go & Book Ihren Lieblingsservice",
          "New": "Neu",
          "We'll let you know when we\nget news for you":
              "Wir benachrichtigen dich, wenn wir Neuigkeiten für dich haben",
          "The Perfect choice for": "Die perfekte Wahl für",
          "your future": "deine Zukunft",
          "Login With Phone Number": "Melden Sie sich mit der Telefonnummer an",
          "Verification Code": "Bestätigungs-Code",
          "We have sent the code verification to":
              "Wir haben die Code-Bestätigung an gesendet",
          "Didn't receive code?": "Code nicht erhalten?",
          "Resend New Code": "Neuen Code erneut senden",
          "Verify": "Verifizieren",
          "Please enter your valid OTP": "Bitte geben Sie Ihr gültiges OTP ein",
          "Create Your New Password": "Erstellen Sie Ihr neues Passwort",
          "Conform Password": "Passen Sie das Passwort an",
          "Reset Password": "Passwort zurücksetzen",
          "Please enter your phone number to request a\npassword reset":
              "Bitte geben Sie Ihre Telefonnummer ein, um eine\nZurücksetzung des Passworts anzufordern",
          "Request OTP": "OTP anfordern",
          "You remember your password?": "Erinnern Sie sich an Ihr Passwort?",
          "Review Summary": "Zusammenfassung",
          "Remove": "Entfernen",
          "Add": "Hinzufügen",
          "Pay from Wallet": "Von Wallet bezahlen",
          "Wallet Balance": "Wallet-Guthaben",
          "Available for Payment ": "Zur Zahlung verfügbar",
          "Congratulations!": "Glückwunsch!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "erfolgreich\n gebucht. Sie können Ihre Buchung\n im Menü Profil überprüfen",
          "View E-Receipt": "E-Quittung anzeigen",
          "Select Payment Method": "Wählen Sie die Zahlungsmethode",
          "Add Your payment information":
              "Fügen Sie Ihre Zahlungsinformationen hinzu",
          "What number is written on card?":
              "Welche Nummer steht auf der Karte?",
          "Number behind the card": "Nummer hinter der Karte",
          "CVV": "CVV",
          "MM/YY": "MM/JJ",
          "Expiry Date": "Verfallsdatum",
          "Payment card is valid": "Zahlungskarte ist gültig",
          "Select Country": "Land auswählen",
          "Get Started!": "Loslegen!",
          "Create an account to continue.":
              "Erstellen Sie ein Konto, um fortzufahren.",
          "Email Address": "E-Mail-Addresse",
          "Referral code (optional)": "Empfehlungscode (optional)",
          "By creating an account,you agree to our":
              "Indem Sie ein Konto erstellen, stimmen Sie unseren zu",
          "Terms and Condition": "Geschäftsbedingung",
          "Please select Terms and Condition": "Bitte AGB auswählen",
          "Already have an account?": "Sie haben bereits ein Konto?",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "Verwalten Sie Ihre Objekte ganz einfach und \nerhalten Sie sofortige Benachrichtigungen über Antworten",
          "Listing Agent": "Auflistungsagent",
          "Partner": "Partner",
          "Overview": "Überblick",
          "Read more": "Weiterlesen",
          "Show less": "Zeige weniger",
          "Facillities": "Einrichtungen",
          "Location": "Standort",
          "Price": "Preis",
          "Book": "Buch",
          "Contacted": "Kontaktiert",
          "Enquiry Already Send!!": "Anfrage bereits gesendet!!",
          "Inquiry": "Anfrage",
          "Please login and send enquery": "Bitte einloggen und Anfrage senden",
          "Update": "Aktualisieren",
          "Add Wallet": "Geldbörse hinzufügen",
          "Your current Balance": "Ihr aktuelles Guthaben",
          "Add Amount": "Betrag hinzufügen",
          "Refer a Friend": "Empfehlen Sie einen Freund",
          "Share the referral link with your friends":
              "Teilen Sie den Empfehlungslink mit Ihren Freunden",
          "History": "Geschichte",
          "ADD AMOUNT": "BETRAG HINZUFÜGEN",
          "Please don`t press back until the transaction is complete":
              "Bitte drücken Sie nicht zurück, bis die Transaktion abgeschlossen ist",
          "Amount": "Menge",
          "days": "Tage",
          "Booking Date": "Buchungsdatum",
          "/night": "/Nacht",
          "Beds": "Betten",
          "Bath": "Bad",
          "sqft": "qm",
          "About this space": "Über diesen Raum",
          "What this place offers": "Was dieser Ort bietet",
          "Allowed Max": "Erlaubt max",
          "Guest": "Gast",
          "Not Paid": "Nicht bezahlt",
          "Friend get": "Freund bekommen",
          "on their first complete\ntransaction":
              "bei ihrer ersten vollständigen\nTransaktion",
          "You get": "Du erhältst",
          "on your wallet": "auf deinem Geldbeutel",
          "for Each\n Friend you refer":
              "für jeden\n Freund, den Sie empfehlen",
          "Earn": "Verdienen",
          "Are you sure you want to delete account?":
              "Möchten Sie das Konto wirklich löschen?",
          "Delete Account": "Konto löschen",
          "founds": "findet",
        },
        'in_US': {
          "My Booking": "Pemesanan Saya",
          "Wallet": "Dompet",
          "Profile": "Profil",
          "Notification": "Pemberitahuan",
          "Country": "Negara",
          "Language": "Bahasa",
          "English(US)": "Inggris(AS)",
          "Help Center": "Pusat Bantuan",
          "Invite Friends": "Mengundang teman-teman",
          "Logout": "Keluar",
          "Dark Mode": "Mode Gelap",
          "Are you sure you want to log out?":
              "Apakah Anda yakin ingin keluar?,",
          "Cancle": "Batal",
          "Yes, Remove": "Ya, Hapus",
          "Coupons": "Kupon",
          "Property Title": "Judul Properti",
          "Full Name": "Nama lengkap",
          "Please enter your name": "Silahkan masukan nama anda",
          "Book For Someone": "Pesan Untuk Seseorang",
          "Your Information Details": "Detail Informasi Anda",
          "First Name": "Nama depan",
          "Please enter your first name": "Masukkan nama depan Anda",
          "Last Name": "Nama keluarga",
          "Please enter your last name": "Masukkan nama belakang Anda",
          "Email": "Surel",
          "Please enter your email": "Masukkan email Anda",
          "Mobile Number": "Nomor handphone",
          "Please enter your number": "Silakan masukkan nomor Anda",
          "Continue": "Melanjutkan",
          "Please fill all required fields":
              "Harap isi semua bidang yang wajib diisi",
          "Book Real Estate": "Pesan Real Estat",
          "Select Date": "Pilih Tanggal",
          "Check in": "Mendaftar",
          "Check out": "Periksa",
          "Number of Guest": "Jumlah Tamu",
          "Note to Owner (optional)": "Catatan untuk Pemilik (opsional)",
          "Notes": "Catatan",
          "Booking for someone": "Pemesanan untuk seseorang",
          "Home": "Rumah",
          "Search": "Mencari",
          "Favorite": "Favorit",
          "Account": "Akun",
          "BUY": "MEMBELI",
          "Sorry, Search Data Not Found":
              "Maaf, Data Pencarian Tidak Ditemukan",
          "Sorry, there is no any nearby \n category or data not found":
              "Maaf, tidak ada \n kategori atau data terdekat yang tidak ditemukan",
          "Apply": "Menerapkan",
          "Available coupons": "Kupon yang tersedia",
          "Use": "Menggunakan",
          "E-Receipt": "Tanda terima elektronik",
          "Date": "Tanggal",
          "Tax": "Pajak",
          "Coupon": "Kupon",
          "Total": "Total",
          "Name": "Nama",
          "Phone Number": "Nomor telepon",
          "Payment Title": "Judul Pembayaran",
          "Transaction ID": "ID transaksi",
          "Copy": "Menyalin",
          "Status": "Status",
          "Paid": "Dibayar",
          "Review": "Tinjauan",
          "Leave a Review": "Tinggalkan Ulasan",
          "How was your experience": "Bagaimana pengalaman Anda",
          "Write Your Review": "Tulis Ulasan Anda",
          "Your review here...": "Ulasan Anda di sini...",
          "Maybe Later": "Mungkin nanti",
          "Submit": "Kirim",
          "Helps & FAQs": "Bantuan & FAQ",
          "Favorites": "Favorit",
          "Sorry, Favorite List Empty": "Maaf, Daftar Favorit Kosong",
          "Remove from Favorites?": "Hapus dari Favorit?",
          "Featured": "Unggulan",
          "Gallary": "Galeri",
          "Hello Welcome 👋": "Halo Selamat Datang 👋",
          "User": "Pengguna",
          "See All": "Lihat semua",
          "Our Recommendation": "Rekomendasi Kami",
          "Search...": "Mencari...",
          "Suggested": "Disarankan",
          "Let's sign you in.": "Izinkan Anda masuk.",
          "Welcome back. You've been missed!":
              "Selamat Datang kembali. Anda telah dirindukan!",
          "Please enter your mobile number":
              "Silakan masukkan nomor ponsel Anda",
          "Please enter your password": "Silakan masukkan kata sandi Anda",
          "Password": "Kata sandi",
          "Remember me": "Ingat saya",
          "Forgot Password?": "Tidak ingat kata sandi?",
          "Login": "Gabung",
          "OR": "ATAU",
          "Continue as a Guest": "Lanjutkan sebagai Tamu",
          "Don't have an account?": "Belum punya akun?",
          "Sign Up": "Mendaftar",
          "Massage": "Pijat",
          "Active": "Aktif",
          "Completed": "Lengkap",
          "Go & Book your favorite service":
              "Pergi & Pesan layanan favorit Anda",
          "New": "Baru",
          "We'll let you know when we\nget news for you":
              "Kami akan memberi tahu Anda saat kami\nmendapatkan berita untuk Anda",
          "The Perfect choice for": "Pilihan sempurna untuk",
          "your future": "masa depanmu",
          "Login With Phone Number": "Masuk Dengan Nomor Telepon",
          "Verification Code": "Kode verifikasi",
          "We have sent the code verification to":
              "Kami telah mengirimkan kode verifikasi ke",
          "Didn't receive code?": "Tidak menerima kode?",
          "Resend New Code": "Kirim Ulang Kode Baru",
          "Verify": "Memeriksa",
          "Please enter your valid OTP": "Masukkan OTP Anda yang valid",
          "Create Your New Password": "Buat Kata Sandi Baru Anda",
          "Conform Password": "Sesuaikan Kata Sandi",
          "Reset Password": "Atur Ulang Kata Sandi",
          "Please enter your phone number to request a\npassword reset":
              "Masukkan nomor telepon Anda untuk meminta\nsetel ulang sandi",
          "Request OTP": "Minta OTP",
          "You remember your password?": "Anda ingat kata sandi Anda?",
          "Review Summary": "rangkuman ulasan",
          "Remove": "Menghapus",
          "Add": "Menambahkan",
          "Pay from Wallet": "Bayar dari Dompet",
          "Wallet Balance": "Saldo Dompet",
          "Available for Payment ": "Tersedia untuk Pembayaran",
          "Congratulations!": "Selamat!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "berhasil\n dipesan. Anda dapat mengubah pemesanan Anda\n di menu Profil",
          "View E-Receipt": "Lihat Tanda Terima Elektronik",
          "Select Payment Method": "Pilih metode pembayaran",
          "Add Your payment information": "Tambahkan informasi pembayaran Anda",
          "What number is written on card?":
              "Nomor berapa yang tertulis di kartu?",
          "Number behind the card": "Nomor di belakang kartu",
          "CVV": "CVV",
          "MM/YY": "mm/ttt",
          "Expiry Date": "Tanggal kadaluarsa",
          "Payment card is valid": "Kartu pembayaran valid",
          "Select Country": "Pilih negara",
          "Get Started!": "Memulai!",
          "Create an account to continue.": "Buat akun untuk melanjutkan.",
          "Email Address": "Alamat email",
          "Referral code (optional)": "Kode rujukan (opsional)",
          "By creating an account,you agree to our":
              "Dengan membuat akun, Anda menyetujui kami",
          "Terms and Condition": "Syarat dan Ketentuan",
          "Please select Terms and Condition":
              "Silakan pilih Syarat dan Ketentuan",
          "Already have an account?": "Sudah memiliki akun?",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "Kelola properti Anda dengan mudah dan \ndapatkan peringatan instan tentang respons",
          "Listing Agent": "Daftar Agen",
          "Partner": "Mitra",
          "Overview": "Ringkasan",
          "Read more": "Baca selengkapnya",
          "Show less": "Tampilkan lebih sedikit",
          "Facillities": "Fasilitas",
          "Location": "Lokasi",
          "Price": "Harga",
          "Book": "Buku",
          "Contacted": "Dihubungi",
          "Enquiry Already Send!!": "Permintaan Sudah Kirim!!",
          "Inquiry": "Pertanyaan",
          "Please login and send enquery": "Silakan masuk dan kirim pertanyaan",
          "Update": "Memperbarui",
          "Add Wallet": "Tambahkan Dompet",
          "Your current Balance": "Saldo Anda saat ini",
          "Add Amount": "Tambahkan Jumlah",
          "Refer a Friend": "Menunjuk teman",
          "Share the referral link with your friends":
              "Bagikan tautan rujukan dengan teman-teman Anda",
          "History": "Sejarah",
          "ADD AMOUNT": "TAMBAH JUMLAH",
          "Please don`t press back until the transaction is complete":
              "Tolong jangan tekan kembali sampai transaksi selesai",
          "Amount": "Jumlah",
          "days": "hari",
          "Booking Date": "Tanggal Pemesanan",
          "/night": "/malam",
          "Beds": "Tempat tidur",
          "Bath": "Mandi",
          "sqft": "kaki persegi",
          "About this space": "Tentang ruang ini",
          "What this place offers": "Apa yang ditawarkan tempat ini",
          "Allowed Max": "Maks",
          "Guest": "Tamu",
          "Not Paid": "Tidak dibayarkan",
          "Friend get": "Teman dapatkan",
          "on their first complete\ntransaction":
              "pada transaksi\nselesai pertama mereka",
          "You get": "Anda mendapatkan",
          "on your wallet": "di dompet Anda",
          "for Each\n Friend you refer":
              "untuk Setiap\n Teman yang Anda referensikan",
          "Earn": "Menghasilkan",
          "Are you sure you want to delete account?":
              "Apakah Anda yakin ingin menghapus akun?",
          "Delete Account": "Hapus akun",
          "founds": "temuan",
        },
        'pt_US': {
          "My Booking": "Minha reserva",
          "Wallet": "Carteira",
          "Profile": "Perfil",
          "Notification": "Notificação",
          "Country": "País",
          "Language": "Linguagem",
          "English(US)": "Inglês (EUA)",
          "Help Center": "Centro de ajuda",
          "Invite Friends": "Convide amigos",
          "Logout": "Sair",
          "Dark Mode": "Modo Escuro",
          "Are you sure you want to log out?": "Tem certeza que deseja sair?,",
          "Cancle": "Cântico",
          "Yes, Remove": "Sim, remover",
          "Coupons": "cupons",
          "Property Title": "Título da propriedade",
          "Full Name": "Nome completo",
          "Please enter your name": "Por favor, insira seu nome",
          "Book For Someone": "Reserve Para Alguém",
          "Your Information Details": "Seus detalhes de informação",
          "First Name": "Primeiro nome",
          "Please enter your first name":
              "por favor entre com seu primeiro nome",
          "Last Name": "Sobrenome",
          "Please enter your last name": "Por favor insira seu sobrenome",
          "Email": "E-mail",
          "Please enter your email": "Por favor introduza o seu e-mail",
          "Mobile Number": "Número de telemóvel",
          "Please enter your number": "Por favor, digite seu número",
          "Continue": "Continuar",
          "Please fill all required fields":
              "Por favor, preencha todos os campos obrigatórios",
          "Book Real Estate": "Reserve Imóveis",
          "Select Date": "Selecione a data",
          "Check in": "Check-in",
          "Check out": "Confira",
          "Number of Guest": "Número de convidados",
          "Note to Owner (optional)": "Nota ao Proprietário (opcional)",
          "Notes": "Notas",
          "Booking for someone": "Reserva para alguém",
          "Home": "Lar",
          "Search": "Procurar",
          "Favorite": "Favorito",
          "Account": "Conta",
          "BUY": "COMPRAR",
          "Sorry, Search Data Not Found":
              "Desculpe, dados de pesquisa não encontrados",
          "Sorry, there is no any nearby \n category or data not found":
              "Desculpe, não há nenhuma categoria \n próxima ou dados não encontrados",
          "Apply": "Aplicar",
          "Available coupons": "cupons disponíveis",
          "Use": "Usar",
          "E-Receipt": "Recibo eletrônico",
          "Date": "Data",
          "Tax": "Imposto",
          "Coupon": "Cupom",
          "Total": "Total",
          "Name": "Nome",
          "Phone Number": "Número de telefone",
          "Payment Title": "Título de Pagamento",
          "Transaction ID": "ID da transação",
          "Copy": "cópia de",
          "Status": "Status",
          "Paid": "Pago",
          "Review": "Análise",
          "Leave a Review": "Deixe um comentário",
          "How was your experience": "Como foi sua experiência",
          "Write Your Review": "Escreva sua revisão",
          "Your review here...": "Sua opinião aqui...",
          "Maybe Later": "Talvez mais tarde",
          "Submit": "Enviar",
          "Helps & FAQs": "Ajuda e perguntas frequentes",
          "Favorites": "Favoritos",
          "Sorry, Favorite List Empty": "Desculpe, lista de favoritos vazia",
          "Remove from Favorites?": "Remover dos favoritos?",
          "Featured": "Apresentou",
          "Gallary": "galeria",
          "Hello Welcome 👋": "Olá bem vindo 👋",
          "User": "Do utilizador",
          "See All": "ver tudo",
          "Our Recommendation": "Nossa recomendação",
          "Search...": "Procurar...",
          "Suggested": "Sugerido",
          "Let's sign you in.": "Vamos fazer seu login.",
          "Welcome back. You've been missed!":
              "Bem vindo de volta. Você fez falta!",
          "Please enter your mobile number":
              "Por favor, insira seu número de telefone",
          "Please enter your password": "Por favor, insira sua senha",
          "Password": "Senha",
          "Remember me": "Lembre de mim",
          "Forgot Password?": "Esqueceu sua senha?",
          "Login": "Conecte-se",
          "OR": "OU",
          "Continue as a Guest": "Continuar como convidado",
          "Don't have an account?": "Não tem uma conta?",
          "Sign Up": "Inscrever-se",
          "Massage": "Massagem",
          "Active": "Ativo",
          "Completed": "Concluído",
          "Go & Book your favorite service":
              "Vá & Reserve o seu serviço favorito",
          "New": "Novo",
          "We'll let you know when we\nget news for you":
              "Avisaremos quando\ntivermos notícias para você",
          "The Perfect choice for": "A escolha perfeita para",
          "your future": "seu futuro",
          "Login With Phone Number": "Entrar com número de telefone",
          "Verification Code": "Código de verificação",
          "We have sent the code verification to":
              "Enviamos a verificação do código para",
          "Didn't receive code?": "Não recebeu o código?",
          "Resend New Code": "Reenviar Novo Código",
          "Verify": "Verificar",
          "Please enter your valid OTP": "Insira seu OTP válido",
          "Create Your New Password": "Crie sua nova senha",
          "Conform Password": "Conforme senha",
          "Reset Password": "Redefinir senha",
          "Please enter your phone number to request a\npassword reset":
              "Digite seu número de telefone para solicitar uma\nredefinição de senha",
          "Request OTP": "Solicitar OTP",
          "You remember your password?": "Você se lembra da sua senha?",
          "Review Summary": "Resumo da revisão",
          "Remove": "Remover",
          "Add": "Adicionar",
          "Pay from Wallet": "Pagar com Carteira",
          "Wallet Balance": "Saldo da Carteira",
          "Available for Payment ": "Disponível para pagamento",
          "Congratulations!": "Parabéns!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "reservado com sucesso. Pode consultar a sua reserva\n no menu Perfil",
          "View E-Receipt": "Ver recibo eletrônico",
          "Select Payment Method": "Selecione o método de pagamento",
          "Add Your payment information":
              "Adicione suas informações de pagamento",
          "What number is written on card?":
              "Que número está escrito no cartão?",
          "Number behind the card": "Número atrás do cartão",
          "CVV": "CVV",
          "MM/YY": "MM/AA",
          "Expiry Date": "Data de validade",
          "Payment card is valid": "O cartão de pagamento é válido",
          "Select Country": "Selecione o pais",
          "Get Started!": "Iniciar!",
          "Create an account to continue.": "Crie uma conta para continuar.",
          "Email Address": "Endereço de email",
          "Referral code (optional)": "Código de indicação (opcional)",
          "By creating an account,you agree to our":
              "Ao criar uma conta, você concorda com nossos",
          "Terms and Condition": "Termos e Condições",
          "Please select Terms and Condition":
              "Selecione os Termos e Condições",
          "Already have an account?": "já tem uma conta?",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "Gerencie suas propriedades com facilidade e \nobtenha alertas instantâneos sobre as respostas",
          "Listing Agent": "Agente de Listagem",
          "Partner": "Parceiro",
          "Overview": "Visão geral",
          "Read more": "Consulte Mais informação",
          "Show less": "Mostre menos",
          "Facillities": "Instalações",
          "Location": "Localização",
          "Price": "Preço",
          "Book": "Livro",
          "Contacted": "contatado",
          "Enquiry Already Send!!": "Inquérito já enviado!!",
          "Inquiry": "Investigação",
          "Please login and send enquery":
              "Por favor, faça o login e envie a consulta",
          "Update": "Atualizar",
          "Add Wallet": "Adicionar Carteira",
          "Your current Balance": "Seu saldo atual",
          "Add Amount": "Adicionar valor",
          "Refer a Friend": "Indique um Amigo",
          "Share the referral link with your friends":
              "Compartilhe o link de indicação com seus amigos",
          "History": "História",
          "ADD AMOUNT": "ADICIONAR VALOR",
          "Please don`t press back until the transaction is complete":
              "Por favor, não pressione de volta até que a transação seja concluída",
          "Amount": "Quantia",
          "days": "dias",
          "Booking Date": "Data da reserva",
          "/night": "/noite",
          "Beds": "Camas",
          "Bath": "Banho",
          "sqft": "pés quadrados",
          "About this space": "Sobre este espaço",
          "What this place offers": "O que este lugar oferece",
          "Allowed Max": "Máximo Permitido",
          "Guest": "Convidado",
          "Not Paid": "Não pago",
          "Friend get": "Amigo pegue",
          "on their first complete\ntransaction":
              "na primeira\ntransação concluída",
          "You get": "você consegue",
          "on your wallet": "na sua carteira",
          "for Each\n Friend you refer": "para cada\n amigo que você indicar",
          "Earn": "Ganhar",
          "Are you sure you want to delete account?":
              "Tem certeza de que deseja excluir a conta?",
          "Delete Account": "Deletar conta",
          "founds": "funda",
        },
        'ZA_US': {
          "My Booking": "My bespreking",
          "Wallet": "Beursie",
          "Profile": "Profiel",
          "Notification": "Kennisgewing",
          "Country": "Land",
          "Language": "Taal",
          "English(US)": "Engels (VS)",
          "Help Center": "Hulp Sentrum",
          "Invite Friends": "Nooi vriende",
          "Logout": "Teken uit",
          "Dark Mode": "Donker modus",
          "Are you sure you want to log out?": "Is jy seker jy wil afmeld?,",
          "Cancle": "Kankel",
          "Yes, Remove": "Ja, verwyder",
          "Coupons": "Koepons",
          "Property Title": "Eiendomstitel",
          "Full Name": "Volle naam",
          "Please enter your name": "Voer asseblief jou naam in",
          "Book For Someone": "Boek Vir Iemand",
          "Your Information Details": "Jou Inligting Besonderhede",
          "First Name": "Eerste naam",
          "Please enter your first name": "Voer asseblief jou voornaam in",
          "Last Name": "Van",
          "Please enter your last name": "Voer asseblief jou van in",
          "Email": "E-pos",
          "Please enter your email": "Voer asseblief jou e-posadres in",
          "Mobile Number": "Selfoon nommer",
          "Please enter your number": "Voer asseblief jou nommer in",
          "Continue": "Aanhou",
          "Please fill all required fields":
              "Vul asseblief alle vereiste velde in",
          "Book Real Estate": "Bespreek Eiendom",
          "Select Date": "Kies Datum",
          "Check in": "Inboek",
          "Check out": "Uitteken",
          "Number of Guest": "Aantal gaste",
          "Note to Owner (optional)": "Nota aan eienaar (opsioneel)",
          "Notes": "Notas",
          "Booking for someone": "Bespreking vir iemand",
          "Home": "Tuis",
          "Search": "Soek",
          "Favorite": "Gunsteling",
          "Account": "Rekening",
          "BUY": "KOOP",
          "Sorry, Search Data Not Found": "Jammer, soekdata nie gevind nie",
          "Sorry, there is no any nearby \n category or data not found":
              "Jammer, daar is geen nabygeleë \n kategorie of data nie gevind nie",
          "Apply": "Doen aansoek",
          "Available coupons": "Beskikbare koepons",
          "Use": "Gebruik",
          "E-Receipt": "E-kwitansie",
          "Date": "Datum",
          "Tax": "Belasting",
          "Coupon": "Koepon",
          "Total": "Totaal",
          "Name": "Naam",
          "Phone Number": "Telefoon nommer",
          "Payment Title": "Betaling Titel",
          "Transaction ID": "Transaksie ID",
          "Copy": "Kopieer",
          "Status": "Status",
          "Paid": "Betaal",
          "Review": "Resensie",
          "Leave a Review": "Laat 'n resensie",
          "How was your experience": "Hoe was jou ervaring",
          "Write Your Review": "Skryf jou resensie",
          "Your review here...": "Jou resensie hier...",
          "Maybe Later": "Miskien later",
          "Submit": "Indien",
          "Helps & FAQs": "Hulp en Gereelde Vrae",
          "Favorites": "Gunstelinge",
          "Sorry, Favorite List Empty": "Jammer, gunstelinglys is leeg",
          "Remove from Favorites?": "Verwyder uit gunstelinge?",
          "Featured": "Uitgestalte",
          "Gallary": "Galery",
          "Hello Welcome 👋": "Hallo Welkom 👋",
          "User": "Gebruiker",
          "See All": "Sien Alles",
          "Our Recommendation": "Ons Aanbeveling",
          "Search...": "Soek...",
          "Suggested": "Voorgestel",
          "Let's sign you in.": "Kom ons meld jou aan.",
          "Welcome back. You've been missed!": "Welkom terug. Jy is gemis!",
          "Please enter your mobile number":
              "Voer asseblief jou selfoonnommer in",
          "Please enter your password": "Tik asseblief jou wagwoord",
          "Password": "Wagwoord",
          "Remember me": "Onthou my",
          "Forgot Password?": "Wagwoord vergeet?",
          "Login": "Teken aan",
          "OR": "OF",
          "Continue as a Guest": "Gaan voort as 'n gas",
          "Don't have an account?": "Het jy nie 'n rekening nie?",
          "Sign Up": "Teken aan",
          "Massage": "Masseer",
          "Active": "Aktief",
          "Completed": "Voltooi",
          "Go & Book your favorite service":
              "Gaan en bespreek jou gunsteling diens",
          "New": "Nuut",
          "We'll let you know when we\nget news for you":
              "Ons sal jou laat weet wanneer ons\nnuus vir jou kry",
          "The Perfect choice for": "Die perfekte keuse vir",
          "your future": "jou toekoms",
          "Login With Phone Number": "Teken in met telefoonnommer",
          "Verification Code": "Verifikasie kode",
          "We have sent the code verification to":
              "Ons het die kodeverifikasie gestuur na",
          "Didn't receive code?": "Het u nie kode ontvang nie?",
          "Resend New Code": "Stuur nuwe kode weer",
          "Verify": "Verifieer",
          "Please enter your valid OTP": "Voer asseblief jou geldige OTP in",
          "Create Your New Password": "Skep jou nuwe wagwoord",
          "Conform Password": "Pas wagwoord aan",
          "Reset Password": "Herstel wagwoord",
          "Please enter your phone number to request a\npassword reset":
              "Voer asseblief jou foonnommer in om 'n\nwagwoordterugstelling te versoek",
          "Request OTP": "Versoek OTP",
          "You remember your password?": "Onthou jy jou wagwoord?",
          "Review Summary": "Hersien Opsomming",
          "Remove": "Verwyder",
          "Add": "Voeg by",
          "Pay from Wallet": "Betaal uit Wallet",
          "Wallet Balance": "Beursiebalans",
          "Available for Payment ": "Beskikbaar vir betaling",
          "Congratulations!": "Baie geluk!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "Moderne woonstel suksesvol\n bespreek. Jy kan jou bespreking laai\n op die kieslys Profiel",
          "View E-Receipt": "Kyk na E-kwitansie",
          "Select Payment Method": "Kies Betaalmetode",
          "Add Your payment information": "Voeg jou betalingsinligting by",
          "What number is written on card?":
              "Watter nommer is op kaart geskryf?",
          "Number behind the card": "Nommer agter die kaart",
          "CVV": "CVV",
          "MM/YY": "MM/JJ",
          "Expiry Date": "Verval datum",
          "Payment card is valid": "Betaalkaart is geldig",
          "Select Country": "Kies Land",
          "Get Started!": "Begin!",
          "Create an account to continue.":
              "Skep 'n rekening om voort te gaan.",
          "Email Address": "E-pos adres",
          "Referral code (optional)": "Verwysingskode (opsioneel)",
          "By creating an account,you agree to our":
              "Deur 'n rekening te skep, stem jy in tot ons",
          "Terms and Condition": "Terme en voorwaarde",
          "Please select Terms and Condition":
              "Kies asseblief bepalings en voorwaardes",
          "Already have an account?": "Reeds 'n rekening?",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "Bestuur jou eiendomme met gemak en \nkry onmiddellike waarskuwing oor antwoorde",
          "Listing Agent": "Noteringsagent",
          "Partner": "Vennoot",
          "Overview": "Oorsig",
          "Read more": "Lees meer",
          "Show less": "Wys minder",
          "Facillities": "Fasiliteite",
          "Location": "Ligging",
          "Price": "Prys",
          "Book": "Boek",
          "Contacted": "Gekontak",
          "Enquiry Already Send!!": "Navrae Stuur reeds!!",
          "Inquiry": "Ondersoek",
          "Please login and send enquery":
              "Meld asseblief aan en stuur navraag",
          "Update": "Opdateer",
          "Add Wallet": "Voeg beursie by",
          "Your current Balance": "Jou huidige saldo",
          "Add Amount": "Voeg bedrag by",
          "Refer a Friend": "Verwys 'n Vriend",
          "Share the referral link with your friends":
              "Deel die verwysingskakel met jou vriende",
          "History": "Geskiedenis",
          "ADD AMOUNT": "VOEG BEDRAG BY",
          "Please don`t press back until the transaction is complete":
              "Moet asseblief nie terugdruk totdat die transaksie voltooi is nie",
          "Amount": "Bedrag",
          "days": "dae",
          "Booking Date": "Besprekingsdatum",
          "/night": "/nag",
          "Beds": "Beddens",
          "Bath": "Bad",
          "sqft": "vkft",
          "About this space": "Oor hierdie spasie",
          "What this place offers": "Wat hierdie plek bied",
          "Allowed Max": "Toegelaat Max",
          "Guest": "Gas",
          "Not Paid": "Nie betaal nie",
          "Friend get": "Vriend kry",
          "on their first complete\ntransaction":
              "op hul eerste volledige\ntransaksie",
          "You get": "Jy kry",
          "on your wallet": "op jou beursie",
          "for Each\n Friend you refer": "vir elke\n Vriend wat jy verwys",
          "Earn": "Verdien",
          "Are you sure you want to delete account?":
              "Is jy seker jy wil rekening uitvee?",
          "Delete Account": "Skrap rekening",
          "founds": "bevind",
        },
        'es_US': {
          "My Booking": "Mi reserva",
          "Wallet": "Billetera",
          "Profile": "Perfil",
          "Notification": "Notificación",
          "Country": "País",
          "Language": "Idioma",
          "English(US)": "Inglés (EE. UU.)",
          "Help Center": "Centro de ayuda",
          "Invite Friends": "Invitar a amigos",
          "Logout": "Cerrar sesión",
          "Dark Mode": "Modo oscuro",
          "Are you sure you want to log out?":
              "¿Está seguro de que desea cerrar la sesión?,",
          "Cancle": "Cancelar",
          "Yes, Remove": "Sí, eliminar",
          "Coupons": "cupones",
          "Property Title": "Titulo de propiedad",
          "Full Name": "Nombre completo",
          "Please enter your name": "por favor, escriba su nombre",
          "Book For Someone": "Reservar para alguien",
          "Your Information Details": "Detalles de su información",
          "First Name": "Nombre de pila",
          "Please enter your first name":
              "Por favor, introduzca su nombre de pila",
          "Last Name": "Apellido",
          "Please enter your last name": "Por favor ingrese su apellido",
          "Email": "Correo electrónico",
          "Please enter your email":
              "Por favor introduzca su correo electrónico",
          "Mobile Number": "Número de teléfono móvil",
          "Please enter your number": "Por favor ingrese su número",
          "Continue": "Continuar",
          "Please fill all required fields":
              "por favor llene todos los campos requeridos",
          "Book Real Estate": "Reservar Bienes Raíces",
          "Select Date": "Seleccione fecha",
          "Check in": "Registrarse",
          "Check out": "Verificar",
          "Number of Guest": "Número de invitados",
          "Note to Owner (optional)": "Nota para el propietario (opcional)",
          "Notes": "notas",
          "Booking for someone": "reserva para alguien",
          "Home": "Hogar",
          "Search": "Buscar",
          "Favorite": "Favorito",
          "Account": "Cuenta",
          "BUY": "COMPRAR",
          "Sorry, Search Data Not Found":
              "Lo sentimos, datos de búsqueda no encontrados",
          "Sorry, there is no any nearby \n category or data not found":
              "Lo sentimos, no hay ninguna categoría \n cercana o datos no encontrados",
          "Apply": "Aplicar",
          "Available coupons": "cupones disponibles",
          "Use": "Usar",
          "E-Receipt": "Recibo electrónico",
          "Date": "Fecha",
          "Tax": "Impuesto",
          "Coupon": "Cupón",
          "Total": "Total",
          "Name": "Nombre",
          "Phone Number": "Número de teléfono",
          "Payment Title": "Título de pago",
          "Transaction ID": "ID de transacción",
          "Copy": "Copiar",
          "Status": "Estado",
          "Paid": "Pagado",
          "Review": "Revisar",
          "Leave a Review": "Dejar un comentario",
          "How was your experience": "Cómo fue tu experiencia",
          "Write Your Review": "Escribe tu reseña",
          "Your review here...": "Tu reseña aquí...",
          "Maybe Later": "Quizas mas tarde",
          "Submit": "Entregar",
          "Helps & FAQs": "Ayudas y preguntas frecuentes",
          "Favorites": "Favoritos",
          "Sorry, Favorite List Empty":
              "Lo sentimos, la lista de favoritos está vacía",
          "Remove from Favorites?": "¿Quitar de favoritos?",
          "Featured": "Presentado",
          "Gallary": "galeria",
          "Hello Welcome 👋": "Hola bienvenido 👋",
          "User": "Usuario",
          "See All": "Ver todo",
          "Our Recommendation": "Nuestra recomendación",
          "Search...": "Buscar...",
          "Suggested": "Sugirió",
          "Let's sign you in.": "Vamos a iniciar sesión.",
          "Welcome back. You've been missed!":
              "Bienvenido de nuevo. ¡Te han extrañado!",
          "Please enter your mobile number":
              "Por favor, introduzca su número de móvil",
          "Please enter your password": "Por favor, introduzca su contraseña",
          "Password": "Contraseña",
          "Remember me": "Acuérdate de mí",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "Login": "Acceso",
          "OR": "O",
          "Continue as a Guest": "Continuar como invitado",
          "Don't have an account?": "¿No tienes una cuenta?",
          "Sign Up": "Inscribirse",
          "Massage": "Masaje",
          "Active": "Activo",
          "Completed": "Terminado",
          "Go & Book your favorite service":
              "Ve y Reserva tu servicio favorito",
          "New": "Nuevo",
          "We'll let you know when we\nget news for you":
              "Te avisaremos cuando\ntengamos noticias para ti",
          "The Perfect choice for": "La elección perfecta para",
          "your future": "tu futuro",
          "Login With Phone Number": "Iniciar sesión con número de teléfono",
          "Verification Code": "Código de verificación",
          "We have sent the code verification to":
              "Hemos enviado la verificación del código a",
          "Didn't receive code?": "¿No recibiste el código?",
          "Resend New Code": "Reenviar nuevo código",
          "Verify": "Verificar",
          "Please enter your valid OTP": "Ingrese su OTP válida",
          "Create Your New Password": "Cree su nueva contraseña",
          "Conform Password": "Conforme Contraseña",
          "Reset Password": "Restablecer la contraseña",
          "Please enter your phone number to request a\npassword reset":
              "Ingrese su número de teléfono para solicitar un\nreinicio de contraseña",
          "Request OTP": "Solicitar OTP",
          "You remember your password?": "¿Recuerdas tu contraseña?",
          "Review Summary": "Resumen de la reseña",
          "Remove": "Eliminar",
          "Add": "Agregar",
          "Pay from Wallet": "Pagar desde Monedero",
          "Wallet Balance": "Saldo de la cartera",
          "Available for Payment ": "Disponible para pago",
          "Congratulations!": "¡Felicidades!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "Apartamento moderno\n reservado con éxito. Puedes consultar tu reserva\n en el menú Perfil",
          "View E-Receipt": "Ver recibo electrónico",
          "Select Payment Method": "Seleccionar método de pago",
          "Add Your payment information": "Agrega tu información de pago",
          "What number is written on card?":
              "¿Qué número está escrito en la tarjeta?",
          "Number behind the card": "Número detrás de la tarjeta",
          "CVV": "CVV",
          "MM/YY": "MM/AA",
          "Expiry Date": "Fecha de caducidad",
          "Payment card is valid": "La tarjeta de pago es válida",
          "Select Country": "Seleccionar país",
          "Get Started!": "¡Empezar!",
          "Create an account to continue.": "Crea una cuenta para continuar.",
          "Email Address": "Dirección de correo electrónico",
          "Referral code (optional)": "Código de Referencia (Opcional)",
          "By creating an account,you agree to our":
              "Al crear una cuenta, usted acepta nuestros",
          "Terms and Condition": "Términos y Condiciones",
          "Please select Terms and Condition":
              "Seleccione Términos y condiciones",
          "Already have an account?": "¿Ya tienes una cuenta?",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "Administre sus propiedades con facilidad y \nobtenga alertas instantáneas sobre las respuestas",
          "Listing Agent": "Agente de cotización",
          "Partner": "Pareja",
          "Overview": "Descripción general",
          "Read more": "Leer más",
          "Show less": "Muestra menos",
          "Facillities": "instalaciones",
          "Location": "Ubicación",
          "Price": "Precio",
          "Book": "Libro",
          "Contacted": "contactado",
          "Enquiry Already Send!!": "¡Consulta ya enviada!",
          "Inquiry": "Consulta",
          "Please login and send enquery":
              "Por favor inicie sesión y envíe una consulta",
          "Update": "Actualizar",
          "Add Wallet": "Agregar billetera",
          "Your current Balance": "Su saldo actual",
          "Add Amount": "Añadir cantidad",
          "Refer a Friend": "Recomendar un amigo",
          "Share the referral link with your friends":
              "Comparte el enlace de referencia con tus amigos",
          "History": "Historia",
          "ADD AMOUNT": "AGREGAR CANTIDAD",
          "Please don`t press back until the transaction is complete":
              "Por favor, no presione hacia atrás hasta que se complete la transacción.",
          "Amount": "Cantidad",
          "days": "días",
          "Booking Date": "Fecha para registrarse",
          "/night": "/noche",
          "Beds": "Camas",
          "Bath": "Baño",
          "sqft": "pies cuadrados",
          "About this space": "Sobre este espacio",
          "What this place offers": "Que ofrece este lugar",
          "Allowed Max": "Máximo permitido",
          "Guest": "Invitado",
          "Not Paid": "No pagado",
          "Friend get": "amigo consigue",
          "on their first complete\ntransaction":
              "en su primera transacción completa\n",
          "You get": "Usted obtiene",
          "on your wallet": "en tu billetera",
          "for Each\n Friend you refer": "por cada\n amigo que recomiendes",
          "Earn": "Ganar",
          "Are you sure you want to delete account?":
              "¿Está seguro de que desea eliminar la cuenta?",
          "Delete Account": "Borrar cuenta",
          "founds": "funda",
        },
        'tr_US': {
          "My Booking": "Rezervasyonum",
          "Wallet": "Cüzdan",
          "Profile": "Profil",
          "Notification": "Bildiri",
          "Country": "Ülke",
          "Language": "Dil",
          "English(US)": "Amerikan ingilizcesi)",
          "Help Center": "Yardım Merkezi",
          "Invite Friends": "Arkadaşları davet etmek",
          "Logout": "Çıkış Yap",
          "Dark Mode": "Karanlık Mod",
          "Are you sure you want to log out?":
              "Oturumu kapatmak istediğinizden emin misiniz?,",
          "Cancle": "İptal",
          "Yes, Remove": "Evet, Kaldır",
          "Coupons": "Kuponlar",
          "Property Title": "Mülkiyet Başlığı",
          "Full Name": "Ad Soyad",
          "Please enter your name": "Lütfen adınızı giriniz",
          "Book For Someone": "Birisi İçin Kitap",
          "Your Information Details": "Bilgi Ayrıntılarınız",
          "First Name": "İlk adı",
          "Please enter your first name": "Lütfen isminizi giriniz",
          "Last Name": "Soy isim",
          "Please enter your last name": "Lütfen soyadınızı giriniz",
          "Email": "E-posta",
          "Please enter your email": "Lütfen E-postanızı girin",
          "Mobile Number": "Cep numarası",
          "Please enter your number": "Lütfen numaranızı girin",
          "Continue": "Devam etmek",
          "Please fill all required fields":
              "Lütfen tüm gerekli alanları doldurun",
          "Book Real Estate": "Emlak rezervasyonu yap",
          "Select Date": "Tarih seç",
          "Check in": "Giriş",
          "Check out": "Çıkış yapmak",
          "Number of Guest": "Misafir sayısı",
          "Note to Owner (optional)": "Sahibine Not (isteğe bağlı)",
          "Notes": "notlar",
          "Booking for someone": "birisi için rezervasyon",
          "Home": "Ev",
          "Search": "Aramak",
          "Favorite": "Favori",
          "Account": "Hesap",
          "BUY": "SATIN ALMAK",
          "Sorry, Search Data Not Found": "Üzgünüz, Arama Verisi Bulunamadı",
          "Sorry, there is no any nearby \n category or data not found":
              "Üzgünüz, yakınlarda herhangi bir \n kategori veya veri bulunamadı",
          "Apply": "Uygula",
          "Available coupons": "Mevcut kuponlar",
          "Use": "Kullanmak",
          "E-Receipt": "e-makbuz",
          "Date": "Tarih",
          "Tax": "Vergi",
          "Coupon": "Kupon",
          "Total": "Toplam",
          "Name": "İsim",
          "Phone Number": "Telefon numarası",
          "Payment Title": "Ödeme Başlığı",
          "Transaction ID": "İşlem Kimliği",
          "Copy": "kopyala",
          "Status": "Durum",
          "Paid": "Paralı",
          "Review": "Gözden geçirmek",
          "Leave a Review": "İnceleme bırak",
          "How was your experience": "deneyimin nasıldı",
          "Write Your Review": "Yorumunuzu Yazın",
          "Your review here...": "İncelemeniz burada...",
          "Maybe Later": "Belki sonra",
          "Submit": "Göndermek",
          "Helps & FAQs": "Yardımlar ve SSS",
          "Favorites": "Favoriler",
          "Sorry, Favorite List Empty": "Üzgünüz, Favori Listesi Boş",
          "Remove from Favorites?": "Favorilerden çıkar?",
          "Featured": "Öne Çıkanlar",
          "Gallary": "Galeri",
          "Hello Welcome 👋": "Merhaba hoş geldiniz 👋",
          "User": "kullanıcı",
          "See All": "Hepsini gör",
          "Our Recommendation": "Bizim önerimiz",
          "Search...": "Aramak...",
          "Suggested": "Önerildi",
          "Let's sign you in.": "Giriş yapalım.",
          "Welcome back. You've been missed!": "Tekrar hoşgeldiniz. Özlendin!",
          "Please enter your mobile number":
              "Lütfen telefon numaranızı giriniz",
          "Please enter your password": "Şifrenizi giriniz Lütfen",
          "Password": "Şifre",
          "Remember me": "Beni Hatırla",
          "Forgot Password?": "Parolanızı mı unuttunuz?",
          "Login": "Giriş yapmak",
          "OR": "VEYA",
          "Continue as a Guest": "Misafir olarak devam et",
          "Don't have an account?": "Hesabınız yok mu?",
          "Sign Up": "Üye olmak",
          "Massage": "Masaj",
          "Active": "Aktif",
          "Completed": "Tamamlanmış",
          "Go & Book your favorite service":
              "Git ve en sevdiğin hizmeti rezerve et",
          "New": "Yeni",
          "We'll let you know when we\nget news for you":
              "Sizin için haber aldığımızda size haber vereceğiz",
          "The Perfect choice for": "için mükemmel seçim",
          "your future": "senin geleceğin",
          "Login With Phone Number": "Telefon Numarası ile Giriş Yapın",
          "Verification Code": "Doğrulama kodu",
          "We have sent the code verification to":
              "Kod doğrulamasını şuraya gönderdik:",
          "Didn't receive code?": "Kod almadınız mı?",
          "Resend New Code": "Yeni Kodu Tekrar Gönder",
          "Verify": "Doğrulamak",
          "Please enter your valid OTP": "Lütfen geçerli OTP'nizi girin",
          "Create Your New Password": "Yeni Parolanızı Oluşturun",
          "Conform Password": "Parolayı Onayla",
          "Reset Password": "Şifreyi yenile",
          "Please enter your phone number to request a\npassword reset":
              "Lütfen\nşifre sıfırlama isteğinde bulunmak için telefon numaranızı girin",
          "Request OTP": "OTP talep et",
          "You remember your password?": "Şifreni hatırlıyor musun?",
          "Review Summary": "özeti gözden geçir",
          "Remove": "Kaldırmak",
          "Add": "Eklemek",
          "Pay from Wallet": "Cüzdandan Ödeme",
          "Wallet Balance": "Cüzdan Bakiyesi",
          "Available for Payment ": "Ödeme için uygun",
          "Congratulations!": "Tebrikler!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "başarıyla\n rezerve edildi. Rezervasyonunuzu Profil menüsünden takip edebilirsiniz\n",
          "View E-Receipt": "E-Fatura Görüntüle",
          "Select Payment Method": "ödeme türünü seçin",
          "Add Your payment information": "Ödeme bilgilerinizi ekleyin",
          "What number is written on card?": "Kartta hangi numara yazıyor?",
          "Number behind the card": "Kartın arkasındaki numara",
          "CVV": "özgeçmiş",
          "MM/YY": "AA/YY",
          "Expiry Date": "Son kullanma tarihi",
          "Payment card is valid": "Ödeme kartı geçerli",
          "Select Country": "Ülke Seç",
          "Get Started!": "Başlamak!",
          "Create an account to continue.":
              "Devam etmek için bir hesap oluşturun.",
          "Email Address": "E-posta Adresi",
          "Referral code (optional)": "Referans Kodu (İsteğe Bağlı)",
          "By creating an account,you agree to our":
              "Bir hesap oluşturarak, şunları kabul etmiş olursunuz:",
          "Terms and Condition": "Şartlar ve koşullar",
          "Please select Terms and Condition":
              "Lütfen seçin Şartlar ve Koşullar",
          "Already have an account?": "Zaten hesabınız var mı?",
          "GoProperty": "Playstaxion",
          "Manage your properties with ease and \nget instant alert about responses":
              "Mülklerinizi kolaylıkla yönetin ve yanıtlar hakkında anında uyarı alın",
          "Listing Agent": "Listeleme Aracısı",
          "Partner": "Ortak",
          "Overview": "genel bakış",
          "Read more": "Devamını oku",
          "Show less": "Daha az göster",
          "Facillities": "tesisler",
          "Location": "Konum",
          "Price": "Fiyat",
          "Book": "Kitap",
          "Contacted": "İletişime geçildi",
          "Enquiry Already Send!!": "Soruşturma Zaten Gönderildi!!",
          "Inquiry": "Sorgu",
          "Please login and send enquery":
              "Lütfen giriş yapın ve sorgu gönderin",
          "Update": "Güncelleme",
          "Add Wallet": "Cüzdan Ekle",
          "Your current Balance": "Mevcut Bakiyeniz",
          "Add Amount": "Miktar Ekle",
          "Refer a Friend": "Bir Arkadaşa Öner",
          "Share the referral link with your friends":
              "Referans bağlantısını arkadaşlarınızla paylaşın",
          "History": "Tarih",
          "ADD AMOUNT": "MİKTAR EKLE",
          "Please don`t press back until the transaction is complete":
              "Lütfen işlem tamamlanana kadar geri basmayın",
          "Amount": "Miktar",
          "days": "günler",
          "Booking Date": "Rezervasyon tarihi",
          "/night": "/gece",
          "Beds": "yataklar",
          "Bath": "Banyo",
          "sqft": "metrekare",
          "About this space": "Bu alan hakkında",
          "What this place offers": "Bu yerin sundukları",
          "Allowed Max": "İzin Verilen Maks.",
          "Guest": "Misafir",
          "Not Paid": "Ödenmeyen",
          "Friend get": "arkadaş olsun",
          "on their first complete\ntransaction":
              "tamamladıkları ilk\nişlemlerinde",
          "You get": "sen alırsın",
          "on your wallet": "cüzdanında",
          "for Each\n Friend you refer": "Yönlendirdiğiniz Her\n Arkadaş için",
          "Earn": "Para kazanmak",
          "Are you sure you want to delete account?":
              "Hesabı silmek istediğinizden emin misiniz?",
          "Delete Account": "Hesabı sil",
          "founds": "bulundu",
        },
      };
}
